(()=>{'use strict';
const T=THREE,root=document.getElementById('game'),start=document.getElementById('start'),status=document.getElementById('loadStatus');
const scene=new T.Scene();scene.background=new T.Color(0x0b1830);scene.fog=new T.FogExp2(0x6f86a0,.008);
const camera=new T.PerspectiveCamera(55,innerWidth/innerHeight,.1,220);
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;root.appendChild(renderer.domElement);
scene.add(new T.HemisphereLight(0x9fc8ff,0x23331f,2.2));const moon=new T.DirectionalLight(0xc9dcff,2.2);moon.position.set(-30,45,25);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);scene.add(moon);
const M=(c,r=.8,m=0)=>new T.MeshStandardMaterial({color:c,roughness:r,metalness:m}),G=(c)=>new T.MeshBasicMaterial({color:c,transparent:true,opacity:.85});
const mesh=(g,m)=>{const o=new T.Mesh(g,m);o.castShadow=true;o.receiveShadow=true;return o},box=(w,h,d,m)=>mesh(new T.BoxGeometry(w,h,d),m),cyl=(r,h,m,n=16)=>mesh(new T.CylinderGeometry(r,r*.92,h,n),m),sph=(r,m)=>mesh(new T.SphereGeometry(r,20,14),m),cone=(r,h,m,n=6)=>mesh(new T.ConeGeometry(r,h,n),m);
const sky=box(2,2,2,M(0x172b55));sky.scale.set(180,90,180);sky.position.y=35;scene.add(sky);
const md=sph(5,M(0xeaf3ff,.5));md.position.set(-35,48,-70);scene.add(md);const mh=sph(6,G(0x9fc8ff));mh.position.copy(md.position);mh.scale.set(1,1,.15);scene.add(mh);
for(let i=0;i<70;i++){const s=sph(.035,M(0xe8f2ff,.5));s.position.set((Math.random()-.5)*150,20+Math.random()*55,-45-Math.random()*90);scene.add(s)}
const ground=box(150,.8,150,M(0x263f2c));ground.position.y=-.4;scene.add(ground);const grass=box(130,.18,130,M(0x42633a));grass.position.y=.05;scene.add(grass);
function road(x,z,w,d,r=0){const q=box(w,.08,d,M(0x9c7956));q.position.set(x,.16,z);q.rotation.y=r;scene.add(q)}
road(0,8,7,100);road(-16,-12,5,45,Math.PI/2);road(17,-15,5,38,Math.PI/2);
function tree(x,z,s=1){const g=new T.Group(),t=cyl(.42,2.4,M(0x4a3023),12);t.position.y=1.2;g.add(t);const a=cone(1.9,3.4,M(0x214c32),8);a.position.y=3.2;g.add(a);const b=cone(1.55,2.8,M(0x2d6940),8);b.position.y=4.8;g.add(b);g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
for(const p of [[-24,-27,1.5],[-31,-8,1.2],[-26,16,1.4],[-20,31,1.3],[23,-25,1.5],[31,-5,1.2],[26,18,1.5],[20,34,1.3],[-37,25,1.1],[38,24,1.1]])tree(...p);
for(let i=0;i<28;i++){const side=Math.random()<.5?-1:1;tree(side*(10+Math.random()*27),-35+Math.random()*75,.55+Math.random()*.5)}
function mountain(x,z,s){const g=new T.Group(),b=cone(10*s,18*s,M(0x394b62),7);b.position.y=9*s;g.add(b);const sn=cone(3.2*s,6*s,M(0xcbd8df),7);sn.position.y=17*s;g.add(sn);g.position.set(x,0,z);scene.add(g)}
mountain(-48,-58,2.1);mountain(-5,-72,2.5);mountain(43,-63,2);mountain(55,-20,1.6);
function house(x,z,s=1,rc=0x713c3c){const g=new T.Group(),w=box(5*s,3.2*s,4*s,M(0xb98b62));w.position.y=1.6*s;g.add(w);const r=cone(3.7*s,2.7*s,M(rc),4);r.rotation.y=Math.PI/4;r.position.y=4.5*s;g.add(r);const d=box(.85*s,1.7*s,.15*s,M(0x35241d));d.position.set(0,.85*s,2.08*s);g.add(d);g.position.set(x,0,z);scene.add(g)}
house(-9,-14,1.2);house(9,-14,1.1);house(-10,-25,.9);house(10,-25,.95);house(-18,-17,.8);house(18,-20,.85);
function castle(){const g=new T.Group(),st=M(0x78808b,.7),roof=M(0x28334a);const k=box(13,9,9,st);k.position.y=4.5;g.add(k);for(const x of[-8,8])for(const z of[-5,5]){const t=cyl(2.2,15,st,12);t.position.set(x,7.5,z);g.add(t);const r=cone(2.9,5,roof,8);r.position.set(x,17,z);g.add(r)}const r=cone(8,7,roof,4);r.rotation.y=Math.PI/4;r.position.y=13;g.add(r);g.position.set(0,0,-43);g.scale.setScalar(1.25);scene.add(g)}castle();
function guild(){const g=new T.Group(),w=box(8,5,5,M(0x9d754f));w.position.y=2.5;g.add(w);const r=cone(6,4,M(0x39465e),4);r.rotation.y=Math.PI/4;r.position.y=7;g.add(r);const s=box(4,.9,.25,M(0x5d3b25));s.position.set(0,4.8,2.7);g.add(s);const c=cyl(.65,.16,M(0xd9b14d),8);c.rotation.x=Math.PI/2;c.position.set(0,5,2.86);g.add(c);g.position.set(-16,-11,0);scene.add(g)}guild();
function portal(x,z){const g=new T.Group(),r=new T.Mesh(new T.TorusGeometry(2.6,.25,12,48),G(0x4fc9ff));r.rotation.x=Math.PI/2;r.position.y=2.7;g.add(r);const c=sph(1.8,G(0x2f8cff));c.position.y=2.7;c.scale.z=.15;g.add(c);g.position.set(x,0,z);scene.add(g)}portal(29,27);
function fire(x,z){const g=new T.Group(),b=cyl(.25,1,M(0x4a3020));b.position.y=.5;g.add(b);const f=cone(.5,1.4,G(0xff9a24));f.position.y=1.25;g.add(f);g.position.set(x,0,z);scene.add(g)}[-5,5,-19,19].forEach(x=>fire(x,-11));
const S=Object.assign({level:1,xp:0,hp:100,maxHp:100,gold:25,rep:0,guild:0,bond:15,potions:2,stage:0,kills:0},JSON.parse(localStorage.getItem('otaku3d')||'{}'));
const player={x:0,z:18,model:new T.Group(),walking:false,attack:0,ready:false,mixer:null,actions:{}},lyra={x:-3,z:4,model:new T.Group(),walking:false,ready:false,mixer:null,actions:{}};
scene.add(player.model,lyra.model);player.model.position.set(0,0,18);lyra.model.position.set(-3,0,4);
const mixers=[];
function fit(obj,h){const b=new T.Box3().setFromObject(obj),sz=b.getSize(new T.Vector3());if(sz.y)obj.scale.multiplyScalar(h/sz.y);const b2=new T.Box3().setFromObject(obj);obj.position.y-=b2.min.y;obj.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;n.frustumCulled=false}})}
function weapon(target,type){let hand=null;target.model.traverse(n=>{if(!hand&&/right.?hand|hand_r|mixamorigRightHand/i.test(n.name))hand=n});const g=new T.Group();if(type==='sword'){const blade=box(.12,1.5,.06,M(0xd9e4ff,.25,.8));blade.position.y=.75;g.add(blade);const guard=box(.5,.08,.12,M(0xd9b14d,.35,.7));guard.position.y=.08;g.add(guard);g.rotation.z=-.15}else{const staff=cyl(.055,1.8,M(0x6a452d),10);staff.position.y=.9;g.add(staff);const orb=sph(.16,G(0x69d9ff));orb.position.y=1.85;g.add(orb)}if(hand){hand.add(g);g.position.set(0,0,0)}else{g.position.set(0,1,0);target.model.add(g)}}
function loadHero(target,url,h,type){return new Promise((resolve,reject)=>{const l=new T.GLTFLoader();l.load(url,g=>{const m=g.scene;fit(m,h);target.model=m;target.ready=true;scene.add(m);let idle=g.animations.find(a=>/idle|stand|breath/i.test(a.name))||g.animations[0];let walk=g.animations.find(a=>/walk|run|locomotion/i.test(a.name))||idle;let mixer=new T.AnimationMixer(m);target.mixer=mixer;target.actions={idle:idle?mixer.clipAction(idle):null,walk:walk?mixer.clipAction(walk):null,attack:walk?mixer.clipAction(walk):null};if(target.actions.idle)target.actions.idle.play();mixers.push(mixer);weapon(target,type);resolve()},undefined,reject)})}
const AREN_URL='https://threejs.org/examples/models/gltf/Soldier.glb',LYRA_URL='https://threejs.org/examples/models/gltf/Michelle.glb';
Promise.all([loadHero(player,AREN_URL,3.15,'sword'),loadHero(lyra,LYRA_URL,3.0,'staff')]).then(()=>{start.disabled=false;start.textContent='ENTRER DANS LE MONDE';status.textContent='✓ Aren et Lyra sont chargés.'}).catch(e=>{console.error(e);status.textContent='Échec du chargement des personnages. Recharge la page.'});
function monster(){const g=new T.Group(),b=sph(.65,M(0x566b76)),h=sph(.48,M(0x728994));h.position.y=.55;g.add(b,h);for(const x of[-.16,.16]){const e=sph(.07,G(0xff455c));e.position.set(x,.68,.42);g.add(e)}g.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true});return g}
const enemies=[];for(let i=0;i<7;i++){const a=Math.random()*6.28,r=12+Math.random()*30,e={x:Math.cos(a)*r,z:Math.sin(a)*r,hp:50+S.level*8,cd:0,model:monster()};e.model.position.set(e.x,0,e.z);scene.add(e.model);enemies.push(e)}
const keys={};let started=false,dialog=false,last=performance.now(),attackCd=0,msg=0;
function rank(){return S.guild>=80?'S':S.guild>=60?'A':S.guild>=40?'B':S.guild>=25?'C':S.guild>=12?'D':S.guild>=5?'E':'F'}function need(){return 70+(S.level-1)*50}
function save(){localStorage.setItem('otaku3d',JSON.stringify(S));hud()}function gainxp(n){S.xp+=n;while(S.xp>=need()){S.xp-=need();S.level++;S.maxHp+=15;S.hp=S.maxHp;toast('✨ Niveau '+S.level+' !')}}
function hud(){document.getElementById('stats').innerHTML='<b>AREN · RANG '+rank()+'</b><br>PV '+Math.round(S.hp)+'/'+S.maxHp+' · Niv. '+S.level+' · 💰 '+S.gold+'<div class="bar"><div class="hp" style="width:'+100*S.hp/S.maxHp+'%"></div></div><div class="bar"><div class="xp" style="width:'+100*S.xp/need()+'%"></div></div><span class="small">XP '+S.xp+'/'+need()+' · Réputation '+S.rep+' · Lyra '+S.bond+'</span>';const q=S.stage===0?'Retrouver Lyra':S.stage===1?'Parler à Lyra et accepter la mission':S.stage===2?'Vaincre 3 monstres ('+S.kills+'/3)':S.stage===3?'Retourner voir Lyra':'Explorer le monde';document.getElementById('quest').innerHTML='<b>QUÊTE</b><br>'+q+'<br><span class="small">Guilde '+rank()+' · Potions '+S.potions+'</span>'}
function toast(t){const e=document.getElementById('message');e.textContent=t;e.style.display='block';msg=3}function closeDialog(){dialog=false;document.getElementById('dialog').style.display='none';hud()}
function dialogBox(w,t,opts){dialog=true;document.getElementById('speaker').textContent=w;document.getElementById('dialogText').textContent=t;const c=document.getElementById('choices');c.innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.className='choice';b.textContent=o[0];b.onclick=o[1];c.appendChild(b)});document.getElementById('dialog').style.display='block'}
function interact(){if(!started||dialog)return;if(Math.hypot(player.x-lyra.x,player.z-lyra.z)<4){if(S.stage===0)dialogBox('LYRA','Aren ! Le village n’est que le début. La Guilde des Aventuriers t’attend.',[['Partir avec Lyra',()=>{S.stage=1;S.bond+=8;closeDialog();toast('Lyra rejoint ton aventure.');save()}]]);else if(S.stage===1)dialogBox('LYRA','Une menace rôde dans la forêt. Prouvons notre valeur : trois monstres.',[['Accepter',()=>{S.stage=2;S.guild+=5;closeDialog();toast('Mission F commencée.');save()}]]);else if(S.stage===3)dialogBox('LYRA','Tu as réussi. Regarde au loin… le monde est immense.',[['Continuer',()=>{S.stage=4;S.rep+=10;S.guild+=12;S.gold+=40;gainxp(60);closeDialog();toast('🌌 Une nouvelle région est ouverte.');save()}]]);else toast('Lyra : Notre aventure ne fait que commencer.')}else toast('Approche-toi de Lyra.')}
function potion(){if(S.potions<=0)return toast('Plus de potion.');if(S.hp>=S.maxHp)return toast('PV au maximum.');S.potions--;S.hp=Math.min(S.maxHp,S.hp+45);save();toast('🧪 +45 PV')}
function attack(){if(!started||dialog||attackCd>0)return;attackCd=.48;let best=null,bd=3.4;for(const e of enemies){const d=Math.hypot(player.x-e.x,player.z-e.z);if(d<bd){bd=d;best=e}}if(!best)return toast('Aucun ennemi à portée.');best.hp-=20+S.level*5;player.attack=.3;toast('⚔️ Coup porté');if(best.hp<=0){scene.remove(best.model);enemies.splice(enemies.indexOf(best),1);S.kills++;S.gold+=10;S.rep+=3;S.guild+=2;gainxp(28);if(S.stage===2&&S.kills>=3){S.stage=3;toast('Mission terminée ! Retourne voir Lyra.')}save()}}
function animate(dt){for(const m of mixers)m.update(dt);const a=player.actions,w=a&&(player.attack>0?a.attack:(player.walking?a.walk:a.idle));if(w&&!w.isRunning()){Object.values(a).filter(Boolean).forEach(x=>x.stop());w.reset().fadeIn(.1).play()}if(player.attack>0)player.attack=Math.max(0,player.attack-dt)}
function startGame(){if(!player.ready||!lyra.ready)return;started=true;document.getElementById('intro').style.display='none';toast('Bienvenue à Renaissance. Retrouve Lyra.')}start.onclick=startGame;hud();
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' '){e.preventDefault();attack()}if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='p')potion()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys[k]=true};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys[k]=false});document.querySelectorAll('[data-act]').forEach(b=>b.onpointerdown=()=>({attack,potion,interact}[b.dataset.act])());
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5))});
function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;if(started&&!dialog){let x=(keys.d?1:0)-(keys.a?1:0),z=(keys.s?1:0)-(keys.w?1:0);if(x||z){const l=Math.hypot(x,z);player.x+=x/l*5.5*dt;player.z+=z/l*5.5*dt;player.model.rotation.y=Math.atan2(x,z);player.walking=true}else player.walking=false;player.x=Math.max(-58,Math.min(58,player.x));player.z=Math.max(-58,Math.min(58,player.z));player.model.position.x=player.x;player.model.position.z=player.z;for(const e of enemies){e.cd-=dt;const dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz);if(d<20&&d>.3){e.x+=dx/d*1.8*dt;e.z+=dz/d*1.8*dt;e.model.position.x=e.x;e.model.position.z=e.z;e.model.rotation.y=Math.atan2(dx,dz)}if(d<1.5&&e.cd<=0){e.cd=1;S.hp=Math.max(0,S.hp-(5+S.level*2));if(S.hp===0){S.hp=S.maxHp/2;player.x=0;player.z=18;S.gold=Math.max(0,S.gold-15);toast('Tu as été vaincu.')}save()}}attackCd=Math.max(0,attackCd-dt);hud();if(msg>0){msg-=dt;if(msg<=0)document.getElementById('message').style.display='none'}}animate(dt);camera.position.lerp(new T.Vector3(player.x+10,7.5,player.z+11),.075);camera.lookAt(new T.Vector3(player.x,1.8,player.z));renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();